#!/bin/bash
# commands to be used on the bastion host

file=/etc/origin/master/master-config.yaml
key=projectConfig.projectRequestMessage
value='Please create project using the portal or contact admin@example.com'

# list entry 
ansible masters -m command -a "/usr/local/sbin/yamledit -f ${file} -g ${key}"

# update entry
ansible masters -m command -a "/usr/local/sbin/yamledit -y -f ${file} -o ${file} -r ${key} '${value}'"

# restart master services
ansible masters -m command -a 'systemctl restart atomic-openshift-master-controllers'
ansible masters -m command -a 'systemctl restart atomic-openshift-master-api'
